# Generated by Django 2.1.2 on 2018-12-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('room', models.CharField(max_length=20)),
                ('temperature_f', models.CharField(max_length=4)),
            ],
        ),
    ]
