# Generated by Django 2.1.2 on 2018-12-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20181212_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempmodel',
            name='temperature_f',
            field=models.CharField(max_length=5),
        ),
    ]
