# Generated by Django 2.1.2 on 2018-12-17 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0004_auto_20181216_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempmodel',
            name='room',
            field=models.CharField(choices=[('Kitchen', 'Kitchen'), ('LivingRoom', 'Living Room'), ('ManCave', 'Man Cave'), ('Bedroom', 'Bedroom'), ('SpareBedroom', 'Spare Bedroom'), ('Basement', 'Basement')], max_length=20),
        ),
    ]
