# Generated by Django 2.1.2 on 2018-12-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_auto_20181216_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempmodel',
            name='humidity',
            field=models.FloatField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
