# Generated by Django 2.1.2 on 2019-01-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_mailmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('sensor_id', models.CharField(max_length=30)),
                ('sensor_state', models.CharField(max_length=6)),
            ],
        ),
    ]
