# Generated by Django 2.1.2 on 2019-01-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0010_openmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempmodel',
            name='temperature_outside',
            field=models.FloatField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempmodel',
            name='temperature_setpoint',
            field=models.FloatField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
