# Generated by Django 2.1.2 on 2019-01-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0011_auto_20190129_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempmodel',
            name='temperature_outside',
        ),
        migrations.RemoveField(
            model_name='tempmodel',
            name='temperature_setpoint',
        ),
    ]
