# Generated by Django 2.1.2 on 2019-03-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0012_auto_20190129_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempmodel',
            name='temperature_setpoint',
            field=models.FloatField(default=68, max_length=5),
        ),
    ]
